version: '3.8'

services:
  app1:
    image: ${IMAGE_NAME:-secure-frontend:1.0.0}
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    depends_on:
      - postgres-master
      - redis-master
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
    ports:
      - "3000:3000"

  app2:
    image: ${IMAGE_NAME:-secure-frontend:1.0.0}
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    depends_on:
      - postgres-slave
      - redis-slave
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
    ports:
      - "3001:3000"

  redis-master:
    image: ${REDIS_IMAGE:-redis}:${REDIS_TAG_PROD:-7.4.6-alpine}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"

  redis-slave:
    image: ${REDIS_IMAGE:-redis}:${REDIS_TAG_PROD:-7.4.6-alpine}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  postgres-master:
    image: ${POSTGRES_IMAGE:-postgres}:${POSTGRES_TAG_PROD:-15.13-alpine}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_REPLICATION_PASSWORD}
    ports:
      - "5432:5432"

  postgres-slave:
    image: ${POSTGRES_IMAGE:-postgres}:${POSTGRES_TAG_PROD:-15.13-alpine}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  nginx:
    image: ${NGINX_IMAGE:-nginx}:${NGINX_TAG_PROD:-1.28.0-alpine}
    ports:
      - "80:80"
      - "443:443"

  prometheus:
    image: ${PROM_IMAGE:-prom/prometheus}:${PROM_TAG_PROD:-v3.7.1}
    ports:
      - "9090:9090"

  grafana:
    image: ${GRAFANA_IMAGE:-grafana/grafana}:${GRAFANA_TAG_PROD:-12.2.1}
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
    ports:
      - "3002:3000"

  alertmanager:
    image: ${ALERTMANAGER_IMAGE:-prom/alertmanager}:${ALERTMANAGER_TAG_PROD:-v0.28.1}
    ports:
      - "9093:9093"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-8.19.5}
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION:-8.19.5}
    ports:
      - "5601:5601"