global:
  smtp_smarthost: localhost:587
  smtp_from: alerts@secure-frontend.com
route:
  group_by:
    - alertname
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: web.hook
receivers:
  - name: web.hook
    email_configs:
      - to: admin@secure-frontend.com
        subject: '[{{ .Status }}] {{ .GroupLabels.alertname }}'
        body: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
